/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifiedRouteImport } from './routes/verified'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewslettersIndexRouteImport } from './routes/newsletters.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as NewslettersIdRouteImport } from './routes/newsletters.$id'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'

const VerifiedRoute = VerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersIndexRoute = NewslettersIndexRouteImport.update({
  id: '/newsletters/',
  path: '/newsletters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersIdRoute = NewslettersIdRouteImport.update({
  id: '/newsletters/$id',
  path: '/newsletters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verified': typeof VerifiedRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/newsletters/$id': typeof NewslettersIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/newsletters/': typeof NewslettersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verified': typeof VerifiedRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/newsletters/$id': typeof NewslettersIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/newsletters': typeof NewslettersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/verified': typeof VerifiedRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/newsletters/$id': typeof NewslettersIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/newsletters/': typeof NewslettersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verified'
    | '/articles/$id'
    | '/newsletters/$id'
    | '/articles/'
    | '/newsletters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verified'
    | '/articles/$id'
    | '/newsletters/$id'
    | '/articles'
    | '/newsletters'
  id:
    | '__root__'
    | '/'
    | '/verified'
    | '/articles/$id'
    | '/newsletters/$id'
    | '/articles/'
    | '/newsletters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VerifiedRoute: typeof VerifiedRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  NewslettersIdRoute: typeof NewslettersIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  NewslettersIndexRoute: typeof NewslettersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verified': {
      id: '/verified'
      path: '/verified'
      fullPath: '/verified'
      preLoaderRoute: typeof VerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters/': {
      id: '/newsletters/'
      path: '/newsletters'
      fullPath: '/newsletters/'
      preLoaderRoute: typeof NewslettersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters/$id': {
      id: '/newsletters/$id'
      path: '/newsletters/$id'
      fullPath: '/newsletters/$id'
      preLoaderRoute: typeof NewslettersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VerifiedRoute: VerifiedRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  NewslettersIdRoute: NewslettersIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  NewslettersIndexRoute: NewslettersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
